# 排序节点的组织定义
OrdererOrgs:
  - Name: CERTMANORDER# 名称
    Domain: certmanorder.com # 域名
    Specs: # 节点域名：orderer.certmanorder.com
      - Hostname: orderer # 主机名


# peer节点的组织定义
PeerOrgs:

  # CERTMAN 组织（证书管理系统，需要使用organization节点来查询）
  - Name: CERTMAN
    Domain: certman.com
    Template:
      Count: 2 # 节点域名：peer0.certman.com 和 peer1.certman.com
    Users:
      Count: 1 # 用户：Admin 和 User1

  # CET 组织（独立机构）
  - Name: CET # 名称
    Domain: cet.com # 域名
    Template: # 使用模板定义。Count 指的是该组织下组织节点的个数
      Count: 2 # 节点域名：peer0.cet.com 和 peer1.cet.com
    Users: # 组织的用户信息。Count 指该组织中除了 Admin 之外的用户的个数
      Count: 1 # 用户：Admin 和 User1

  # NCRE 组织（独立机构）
  - Name: NCRE
    Domain: ncre.com
    Template:
      Count: 2 # 节点域名：peer0.ncre.com 和 peer1.ncre.com
    Users:
      Count: 1 # 用户：Admin 和 User1