version: 1.0.0

# GO SDK使用的客户端部分
############  证书系统  ############
client:
  # 客户端所属的组织，必须是organizations定义的组织
  organization: CET
  # 日志级别
  logging:
    level: info
  # MSP证书的根路径
  cryptoconfig:
    path: ../../network/crypto-config

# 通道定义
channels:
  appchannel:
    orderers:
      - orderer.certmanorder.com
    peers:
      peer0.cet.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.cet.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

# 组织配置
organizations:
  CET:
    mspid: "CETMSP"
    cryptoPath: peerOrganizations/cet.com/users/Admin@cet.com/msp
    peers:
      - peer0.cet.com
      - peer1.cet.com

# orderer节点列表
orderers:
  orderer.certmanorder.com:
    url: orderer.certmanorder.com:7050
    # 传递给gRPC客户端构造函数
    grpcOptions:
      ssl-target-name-override: orderer.certman.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true

# peers节点列表
peers:
  # peer节点定义，可以定义多个
  peer0.certman.com:
    # URL用于发送背书和查询请求
    url: peer0.certman.com:7051
    # 传递给gRPC客户端构造函数
    grpcOptions:
      ssl-target-name-override: peer0.certman.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer1.certman.com:
    url: peer1.certman.com:7051
    grpcOptions:
      ssl-target-name-override: peer1.certman.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer0.cet.com:
    url: peer0.cet.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.cet.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer1.cet.com:
    url: peer1.cet.com:7051
    grpcOptions:
      ssl-target-name-override: peer1.cet.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer0.ncre.com:
    url: peer0.ncre.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.ncre.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer1.ncre.com:
    url: peer1.ncre.com:7051
    grpcOptions:
      ssl-target-name-override: peer1.ncre.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true