# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  fabric_network:
    external:
      name: fabric_network

services:

  explorerdb.com:
    image: ghcr.io/hyperledger-labs/explorer-db:latest
    container_name: explorerdb.com
    # platform: lixun/arm64
    hostname: explorerdb.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fabric_network

  explorer.com:
    image: ghcr.io/hyperledger-labs/explorer:latest
    container_name: explorer.com
    # platform: lixun/arm64
    hostname: explorer.com
    environment:
      - DATABASE_HOST=explorerdb.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../crypto-config:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - "8080:8080"
    depends_on:
      explorerdb.com:
        condition: service_healthy
    networks:
      - fabric_network